### PR TITLE
Improvement in Folder Structure

### PR DESCRIPTION
**Pull request by Dhi13man**
Improved code in a lot of files; made generalized; more readable; added comments.

### CODE REVIEW

**Comment by iampavangandhi** [comment]
@Dhi13man Have you tried running all of them before making PR???

**Comment by Dhi13man** [comment]
> 
> 
> @Dhi13man Have you tried running all of them before making PR???

Yes I have tested out my modifications. They are working as intended.

**Comment by iampavangandhi** [comment]
@Dhi13man The main issue in the repo is the programs inside the Cpp Programs folder are not all grouped. Can you group them inside folders.

**Comment by Dhi13man** [comment]
> 
> 
> @Dhi13man The main issue in the repo is the programs inside the Cpp Programs folder are not all grouped. Can you group them inside folders.

Okay I will do that.

**Comment by Dhi13man** [comment]
@iampavangandhi do check out my latest commits. I have added my own contributions and arranged the programs into relevant folders as best as I can.

**Comment by iampavangandhi** [comment]
@Dhi13man Merged :+1:

**Pull request merged**
